Repository gwastro/gwin, pull requests merged in 2018-07, with the labels that each got.

#51 Move example to files
  docs/command-line/gwin_make_workflow.rst
  examples/workflow/GW150914_example/gwin.ini
  examples/workflow/GW150914_example/workflow.ini
Labels: documentation, pr:bug-fix

#57 add some words about <that which can't be mentioned> in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#40 Bump pycbc requirements to 1.12.1
  requirements.txt
  setup.py
Labels: pr:bug-fix, upstream:pycbc

#67 Update emcee.py
  gwin/sampler/emcee.py
Labels: bug
