Repository gwastro/gwin, pull requests merged in 2018-04, with the labels that each got.

#5 Some updates related to GWAstro namespace
  README.rst
  setup.py
Labels: pr:bug-fix

#6 Added some more metadata files
  .github/CODEOWNERS
  CONTRIBUTING.md
  MANIFEST.in
Labels: pr:bug-fix

#8 Updated contribution guide
  CONTRIBUTING.md
Labels: pr:bug-fix

#10 Added code owners based on copyright
  .github/CODEOWNERS
Labels: enhancement

#13 Remove support for reading old-style files
  gwin/sampler/base.py
  gwin/sampler/emcee.py
Labels: pr:backwards-incompatible

#19 Wrapped tex strings to 80-character limit
  docs/_static/css/gwin.css
  gwin/likelihood.py
  gwin/results/scatter_histograms.py
  gwin/workflow.py
Labels: documentation, pr:bug-fix

#20 Added readthedocs configuration
  readthedocs.yml
Labels: documentation

#22 Added RTD badge to README
  README.rst
Labels: documentation

#23 Modified sphinx configuration to run sphinx-apidoc as part of sphinx-build
  docs/Makefile
  docs/conf.py
Labels: documentation
